{{- range untilStep 0 (int $.Values.numEdges) 1 }}
---
apiVersion: v1
kind: Service
metadata:
  name: edgeunderlay-{{.}}
  labels:
    app: edgeunderlay-{{.}}
spec:
  ports:
  - name: rest
    port: 5000
    targetPort: 5000
  - name: flower
    port: 6000
    targetPort: 6000
  selector:
    app: edgeunderlay-{{.}}
{{- end }}