{
 "title": "DasZweite Copy",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Total data traffic generated by FL",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum(node_network_transmit_bytes_total{device=~\"fed.*\", job=\"node_bw\"})+sum(node_network_receive_bytes_total{device=~\"fed.*\", job=\"node_bw\"}))*0.000008"
    }
   ]
  },
  {
   "title": "Overall FL data traffic rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Traffic in Mbps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(node_network_transmit_bytes_total{device=~\"fed.*\", job=\"node_bw\"}[10s])*0.008)+sum(rate(node_network_receive_bytes_total{device=~\"fed.*\", job=\"node_bw\"}[10s])*0.008))/1000"
    }
   ]
  },
  {
   "title": "Rate of sent traffic from Federated server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Total traffic in kbps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_transmit_bytes_total{device=~\"fed.*\", job=\"node_bw\"}[10s])*0.008)"
    }
   ]
  },
  {
   "title": "Rate of received traffic by Federated server",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Total traffic in kbps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(node_network_receive_bytes_total{device=~\"fed.*\", job=\"node_bw\"}[10s])*0.008)"
    }
   ]
  },
  {
   "title": "Average TCP CWND for Cohorts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(tcp_cwnd{flow=\"(DST#10.0.0.101|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_cwnd{flow=\"(DST#10.0.0.102|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_cwnd{flow=\"(DST#10.0.0.103|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_cwnd{flow=\"(DST#10.0.0.104|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_cwnd{flow=\"(DST#10.0.0.105|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_cwnd{flow=\"(DST#10.0.0.106|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_cwnd{flow=\"(DST#10.0.0.107|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_cwnd{flow=\"(DST#10.0.0.108|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_cwnd{flow=\"(DST#10.0.0.109|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_cwnd{flow=\"(DST#10.0.0.110|6000)\", job=\"ss_latency\"})"
    }
   ]
  },
  {
   "title": "Average TCP latency for Cohorts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short", "label": "Latency in ms" }
   ],
   "targets": [
    {
     "expr": "avg(tcp_rtt{flow=\"(DST#10.0.0.101|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_rtt{flow=\"(DST#10.0.0.102|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_rtt{flow=\"(DST#10.0.0.103|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_rtt{flow=\"(DST#10.0.0.104|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_rtt{flow=\"(DST#10.0.0.105|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_rtt{flow=\"(DST#10.0.0.106|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_rtt{flow=\"(DST#10.0.0.107|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_rtt{flow=\"(DST#10.0.0.108|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_rtt{flow=\"(DST#10.0.0.109|6000)\", job=\"ss_latency\"})"
    },
    {
     "expr": "avg(tcp_rtt{flow=\"(DST#10.0.0.110|6000)\", job=\"ss_latency\"})"
    }
   ]
  },
  {
   "title": "Appserv latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "ms" }
   ],
   "targets": [
    {
     "expr": "avg(tcp_rtt{flow=\"(DST#10.0.0.2|5001)\", instance=\"10.0.1.2:9200\", job=\"ss_latency\"})"
    }
   ]
  },
  {
   "title": "Appserv received traffic",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "yaxes": [
    { "format": "short", "label": "Traffic in Mbps" }
   ],
   "targets": [
    {
     "expr": "(sum(rate(node_network_receive_bytes_total{device=~\"appserv.*\", job=\"node_bw\"}[10s])*0.008))/1000"
    }
   ]
  },
  {
   "title": "Loss",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "model_loss" }
   ]
  },
  {
   "title": "Accuracy",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "model_accuracy" }
   ]
  },
  {
   "title": "Cloud MLFO total BW",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "short", "label": "Total traffic in kbps" }
   ],
   "targets": [
    {
     "expr": "((rate(node_network_receive_bytes_total{device=\"cloud.0-eth0\", instance=\"10.0.0.1:9100\", job=\"node_bw\"}[10s]) * 8) + \n(rate(node_network_transmit_bytes_total{device=\"cloud.0-eth0\", instance=\"10.0.0.1:9100\", job=\"node_bw\"}[10s]) * 8) )/1000"
    }
   ]
  },
  {
   "title": "Old Management plane latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(tcp_rtt{flow=\"(DST#10.0.0.1|9000)\", job=\"ss_latency\"}>0)"
    }
   ]
  }
 ]
}